// Mリーグ成績データ（自動生成 - scrape.js が更新します）
// 更新日時: 2026/05/06
window.MLEAGUE_PLAYERS = [
  {
    "rank": 1,
    "name": "下石戟",
    "score": 502.2,
    "games": 44,
    "avg": 2.08,
    "regular_score": 614,
    "semi_score": -25.6,
    "final_score": -86.2,
    "regular_games": 38,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 2,
    "name": "永井孝典",
    "score": 488.2,
    "games": 40,
    "avg": 2.12,
    "regular_score": 503.6,
    "semi_score": 30.9,
    "final_score": -46.3,
    "regular_games": 34,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 3,
    "name": "滝沢和典",
    "score": 399.5,
    "games": 38,
    "avg": 2.33,
    "regular_score": 368.4,
    "semi_score": -56.8,
    "final_score": 87.9,
    "regular_games": 33,
    "semi_games": 4,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 4,
    "name": "渡辺太",
    "score": 374.5,
    "games": 39,
    "avg": 2.27,
    "regular_score": 282.9,
    "semi_score": 91.6,
    "final_score": 0,
    "regular_games": 33,
    "semi_games": 6,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 5,
    "name": "二階堂亜樹",
    "score": 367.4,
    "games": 31,
    "avg": 2.31,
    "regular_score": 271.5,
    "semi_score": 34.8,
    "final_score": 61.1,
    "regular_games": 26,
    "semi_games": 4,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 6,
    "name": "黒沢咲",
    "score": 266.1,
    "games": 32,
    "avg": 2.42,
    "regular_score": 109.9,
    "semi_score": 101.9,
    "final_score": 54.3,
    "regular_games": 26,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 7,
    "name": "園田賢",
    "score": 253.3,
    "games": 43,
    "avg": 2.19,
    "regular_score": 402.7,
    "semi_score": -149.4,
    "final_score": 0,
    "regular_games": 36,
    "semi_games": 7,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 8,
    "name": "中田花奈",
    "score": 243.8,
    "games": 33,
    "avg": 2.3,
    "regular_score": 228.4,
    "semi_score": 5.1,
    "final_score": 10.3,
    "regular_games": 27,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 9,
    "name": "内川幸太郎",
    "score": 209,
    "games": 43,
    "avg": 2.25,
    "regular_score": 320.4,
    "semi_score": -55.6,
    "final_score": -55.8,
    "regular_games": 36,
    "semi_games": 5,
    "final_games": 2,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 10,
    "name": "高宮まり",
    "score": 203.1,
    "games": 33,
    "avg": 2.37,
    "regular_score": 220.7,
    "semi_score": 0.8,
    "final_score": -18.4,
    "regular_games": 27,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 11,
    "name": "渋川難波",
    "score": 176.7,
    "games": 35,
    "avg": 2.4,
    "regular_score": 176.7,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 35,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 12,
    "name": "石井一馬",
    "score": 160.7,
    "games": 39,
    "avg": 2.38,
    "regular_score": 160.7,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 39,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 13,
    "name": "竹内元太",
    "score": 127.5,
    "games": 39,
    "avg": 2.33,
    "regular_score": 151.8,
    "semi_score": -24.3,
    "final_score": 0,
    "regular_games": 33,
    "semi_games": 6,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 14,
    "name": "多井隆晴",
    "score": 123.4,
    "games": 39,
    "avg": 2.36,
    "regular_score": 123.4,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 39,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 15,
    "name": "鈴木優",
    "score": 114.8,
    "games": 34,
    "avg": 2.56,
    "regular_score": 114.8,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 34,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 16,
    "name": "白鳥翔",
    "score": 110.2,
    "games": 35,
    "avg": 2.31,
    "regular_score": 110.2,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 35,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 17,
    "name": "佐々木寿人",
    "score": 99.4,
    "games": 38,
    "avg": 2.43,
    "regular_score": 11.1,
    "semi_score": 68.3,
    "final_score": 20,
    "regular_games": 30,
    "semi_games": 7,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 18,
    "name": "伊達朱里紗",
    "score": 52.3,
    "games": 35,
    "avg": 2.47,
    "regular_score": 91.2,
    "semi_score": -117.3,
    "final_score": 78.4,
    "regular_games": 30,
    "semi_games": 4,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 19,
    "name": "醍醐大",
    "score": 51.1,
    "games": 42,
    "avg": 2.38,
    "regular_score": 113,
    "semi_score": -61.9,
    "final_score": 0,
    "regular_games": 37,
    "semi_games": 5,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 20,
    "name": "茅森早香",
    "score": -34,
    "games": 30,
    "avg": 2.68,
    "regular_score": -58.9,
    "semi_score": 24.9,
    "final_score": 0,
    "regular_games": 25,
    "semi_games": 5,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 21,
    "name": "本田朋広",
    "score": -41.5,
    "games": 42,
    "avg": 2.54,
    "regular_score": -92.4,
    "semi_score": 61.1,
    "final_score": -10.2,
    "regular_games": 35,
    "semi_games": 6,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 22,
    "name": "鈴木大介",
    "score": -43.4,
    "games": 33,
    "avg": 2.67,
    "regular_score": -159.3,
    "semi_score": 176.5,
    "final_score": -60.6,
    "regular_games": 27,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 23,
    "name": "瀬戸熊直樹",
    "score": -60.2,
    "games": 35,
    "avg": 2.59,
    "regular_score": -83.8,
    "semi_score": 44.1,
    "final_score": -20.5,
    "regular_games": 29,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 24,
    "name": "浅井堂岐",
    "score": -61.2,
    "games": 29,
    "avg": 2.64,
    "regular_score": -81.7,
    "semi_score": 20.5,
    "final_score": 0,
    "regular_games": 25,
    "semi_games": 4,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 25,
    "name": "瑞原明奈",
    "score": -72.3,
    "games": 29,
    "avg": 2.66,
    "regular_score": -72.3,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 29,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 26,
    "name": "東城りお",
    "score": -106.6,
    "games": 34,
    "avg": 2.5,
    "regular_score": 6.6,
    "semi_score": -124.2,
    "final_score": 11,
    "regular_games": 28,
    "semi_games": 5,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 27,
    "name": "逢川恵夢",
    "score": -114.3,
    "games": 26,
    "avg": 2.54,
    "regular_score": -114.3,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 28,
    "name": "萩原聖人",
    "score": -120.4,
    "games": 35,
    "avg": 2.6,
    "regular_score": -147.4,
    "semi_score": 52.1,
    "final_score": -25.1,
    "regular_games": 30,
    "semi_games": 4,
    "final_games": 1,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 29,
    "name": "浅見真紀",
    "score": -120.7,
    "games": 25,
    "avg": 2.64,
    "regular_score": -104.1,
    "semi_score": -16.6,
    "final_score": 0,
    "regular_games": 22,
    "semi_games": 3,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 30,
    "name": "岡田紗佳",
    "score": -160.8,
    "games": 27,
    "avg": 2.7,
    "regular_score": -160.8,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 27,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 31,
    "name": "日向藍子",
    "score": -185.8,
    "games": 20,
    "avg": 2.7,
    "regular_score": -185.8,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 20,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 32,
    "name": "阿久津翔太",
    "score": -200,
    "games": 26,
    "avg": 2.69,
    "regular_score": -200,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 33,
    "name": "仲林圭",
    "score": -219.9,
    "games": 32,
    "avg": 2.59,
    "regular_score": -219.9,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 32,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 34,
    "name": "松本吉弘",
    "score": -293.7,
    "games": 26,
    "avg": 2.77,
    "regular_score": -293.7,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 35,
    "name": "勝又健志",
    "score": -310.4,
    "games": 30,
    "avg": 2.79,
    "regular_score": -398.2,
    "semi_score": 87.8,
    "final_score": 0,
    "regular_games": 24,
    "semi_games": 6,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 36,
    "name": "三浦智博",
    "score": -381.9,
    "games": 27,
    "avg": 2.81,
    "regular_score": -381.9,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 27,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 37,
    "name": "HIRO柴田",
    "score": -405,
    "games": 28,
    "avg": 2.86,
    "regular_score": -405,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 28,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 38,
    "name": "堀慎吾",
    "score": -442.6,
    "games": 32,
    "avg": 2.88,
    "regular_score": -442.6,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 32,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 39,
    "name": "小林剛",
    "score": -445,
    "games": 25,
    "avg": 2.92,
    "regular_score": -445,
    "semi_score": 0,
    "final_score": 0,
    "regular_games": 25,
    "semi_games": 0,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  },
  {
    "rank": 40,
    "name": "鈴木たろう",
    "score": -503.6,
    "games": 33,
    "avg": 2.76,
    "regular_score": -334.9,
    "semi_score": -168.7,
    "final_score": 0,
    "regular_games": 29,
    "semi_games": 4,
    "final_games": 0,
    "score_delta": null,
    "rank_delta": null
  }
];
window.MLEAGUE_UPDATED = "2026/05/06";
