// Mリーグ成績データ（自動生成 - scrape.js が更新します）
// 更新日時: 2026/04/17
window.MLEAGUE_PLAYERS = [
  {
    "rank": 1,
    "name": "下石戟",
    "score": 566.1,
    "games": 41,
    "avg": 2.08,
    "regular_score": 614,
    "semi_score": -47.9,
    "regular_games": 38,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 2,
    "name": "永井孝典",
    "score": 507,
    "games": 36,
    "avg": 2.12,
    "regular_score": 503.6,
    "semi_score": 3.4,
    "regular_games": 34,
    "semi_games": 2,
    "score_delta": 60.9,
    "rank_delta": 0
  },
  {
    "rank": 3,
    "name": "園田賢",
    "score": 354.4,
    "games": 39,
    "avg": 2.19,
    "regular_score": 402.7,
    "semi_score": -48.3,
    "regular_games": 36,
    "semi_games": 3,
    "score_delta": 5.2,
    "rank_delta": 0
  },
  {
    "rank": 4,
    "name": "渡辺太",
    "score": 336.9,
    "games": 35,
    "avg": 2.27,
    "regular_score": 282.9,
    "semi_score": 54,
    "regular_games": 33,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 1
  },
  {
    "rank": 5,
    "name": "二階堂亜樹",
    "score": 323.9,
    "games": 29,
    "avg": 2.31,
    "regular_score": 271.5,
    "semi_score": 52.4,
    "regular_games": 26,
    "semi_games": 3,
    "score_delta": -21.6,
    "rank_delta": -1
  },
  {
    "rank": 6,
    "name": "滝沢和典",
    "score": 294.5,
    "games": 35,
    "avg": 2.33,
    "regular_score": 368.4,
    "semi_score": -73.9,
    "regular_games": 33,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 7,
    "name": "内川幸太郎",
    "score": 271.6,
    "games": 38,
    "avg": 2.25,
    "regular_score": 320.4,
    "semi_score": -48.8,
    "regular_games": 36,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 8,
    "name": "黒沢咲",
    "score": 236.5,
    "games": 29,
    "avg": 2.42,
    "regular_score": 109.9,
    "semi_score": 126.6,
    "regular_games": 26,
    "semi_games": 3,
    "score_delta": 61.1,
    "rank_delta": 4
  },
  {
    "rank": 9,
    "name": "中田花奈",
    "score": 205.2,
    "games": 30,
    "avg": 2.3,
    "regular_score": 228.4,
    "semi_score": -23.2,
    "regular_games": 27,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": -1
  },
  {
    "rank": 10,
    "name": "醍醐大",
    "score": 184.9,
    "games": 39,
    "avg": 2.38,
    "regular_score": 113,
    "semi_score": 71.9,
    "regular_games": 37,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": -1
  },
  {
    "rank": 11,
    "name": "高宮まり",
    "score": 179.6,
    "games": 30,
    "avg": 2.37,
    "regular_score": 220.7,
    "semi_score": -41.1,
    "regular_games": 27,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": -1
  },
  {
    "rank": 12,
    "name": "渋川難波",
    "score": 176.7,
    "games": 35,
    "avg": 2.4,
    "regular_score": 176.7,
    "semi_score": 0,
    "regular_games": 35,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": -1
  },
  {
    "rank": 13,
    "name": "石井一馬",
    "score": 160.7,
    "games": 39,
    "avg": 2.38,
    "regular_score": 160.7,
    "semi_score": 0,
    "regular_games": 39,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 14,
    "name": "竹内元太",
    "score": 153.6,
    "games": 36,
    "avg": 2.33,
    "regular_score": 151.8,
    "semi_score": 1.8,
    "regular_games": 33,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 15,
    "name": "多井隆晴",
    "score": 123.4,
    "games": 39,
    "avg": 2.36,
    "regular_score": 123.4,
    "semi_score": 0,
    "regular_games": 39,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 16,
    "name": "鈴木優",
    "score": 114.8,
    "games": 34,
    "avg": 2.56,
    "regular_score": 114.8,
    "semi_score": 0,
    "regular_games": 34,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 17,
    "name": "白鳥翔",
    "score": 110.2,
    "games": 35,
    "avg": 2.31,
    "regular_score": 110.2,
    "semi_score": 0,
    "regular_games": 35,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 18,
    "name": "佐々木寿人",
    "score": 52.9,
    "games": 34,
    "avg": 2.43,
    "regular_score": 11.1,
    "semi_score": 41.8,
    "regular_games": 30,
    "semi_games": 4,
    "score_delta": -55,
    "rank_delta": 0
  },
  {
    "rank": 19,
    "name": "瀬戸熊直樹",
    "score": 22.2,
    "games": 32,
    "avg": 2.59,
    "regular_score": -83.8,
    "semi_score": 106,
    "regular_games": 29,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 20,
    "name": "東城りお",
    "score": -1,
    "games": 30,
    "avg": 2.5,
    "regular_score": 6.6,
    "semi_score": -7.6,
    "regular_games": 28,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 21,
    "name": "鈴木大介",
    "score": -19.6,
    "games": 29,
    "avg": 2.67,
    "regular_score": -159.3,
    "semi_score": 139.7,
    "regular_games": 27,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 22,
    "name": "茅森早香",
    "score": -37.3,
    "games": 27,
    "avg": 2.68,
    "regular_score": -58.9,
    "semi_score": 21.6,
    "regular_games": 25,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 23,
    "name": "本田朋広",
    "score": -45,
    "games": 38,
    "avg": 2.54,
    "regular_score": -92.4,
    "semi_score": 47.4,
    "regular_games": 35,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 1
  },
  {
    "rank": 24,
    "name": "瑞原明奈",
    "score": -72.3,
    "games": 29,
    "avg": 2.66,
    "regular_score": -72.3,
    "semi_score": 0,
    "regular_games": 29,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 1
  },
  {
    "rank": 25,
    "name": "伊達朱里紗",
    "score": -86.2,
    "games": 33,
    "avg": 2.47,
    "regular_score": 91.2,
    "semi_score": -177.4,
    "regular_games": 30,
    "semi_games": 3,
    "score_delta": -44.7,
    "rank_delta": -2
  },
  {
    "rank": 26,
    "name": "萩原聖人",
    "score": -110.2,
    "games": 33,
    "avg": 2.6,
    "regular_score": -147.4,
    "semi_score": 37.2,
    "regular_games": 30,
    "semi_games": 3,
    "score_delta": 18.1,
    "rank_delta": 1
  },
  {
    "rank": 27,
    "name": "逢川恵夢",
    "score": -114.3,
    "games": 26,
    "avg": 2.54,
    "regular_score": -114.3,
    "semi_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": -1
  },
  {
    "rank": 28,
    "name": "浅見真紀",
    "score": -133.3,
    "games": 24,
    "avg": 2.64,
    "regular_score": -104.1,
    "semi_score": -29.2,
    "regular_games": 22,
    "semi_games": 2,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 29,
    "name": "浅井堂岐",
    "score": -154,
    "games": 28,
    "avg": 2.64,
    "regular_score": -81.7,
    "semi_score": -72.3,
    "regular_games": 25,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 30,
    "name": "岡田紗佳",
    "score": -160.8,
    "games": 27,
    "avg": 2.7,
    "regular_score": -160.8,
    "semi_score": 0,
    "regular_games": 27,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 31,
    "name": "日向藍子",
    "score": -185.8,
    "games": 20,
    "avg": 2.7,
    "regular_score": -185.8,
    "semi_score": 0,
    "regular_games": 20,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 32,
    "name": "阿久津翔太",
    "score": -200,
    "games": 26,
    "avg": 2.69,
    "regular_score": -200,
    "semi_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 33,
    "name": "仲林圭",
    "score": -219.9,
    "games": 32,
    "avg": 2.59,
    "regular_score": -219.9,
    "semi_score": 0,
    "regular_games": 32,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 34,
    "name": "松本吉弘",
    "score": -293.7,
    "games": 26,
    "avg": 2.77,
    "regular_score": -293.7,
    "semi_score": 0,
    "regular_games": 26,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 35,
    "name": "三浦智博",
    "score": -381.9,
    "games": 27,
    "avg": 2.81,
    "regular_score": -381.9,
    "semi_score": 0,
    "regular_games": 27,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 36,
    "name": "HIRO柴田",
    "score": -405,
    "games": 28,
    "avg": 2.86,
    "regular_score": -405,
    "semi_score": 0,
    "regular_games": 28,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 37,
    "name": "勝又健志",
    "score": -412.3,
    "games": 27,
    "avg": 2.79,
    "regular_score": -398.2,
    "semi_score": -14.1,
    "regular_games": 24,
    "semi_games": 3,
    "score_delta": 0,
    "rank_delta": 0
  },
  {
    "rank": 38,
    "name": "堀慎吾",
    "score": -442.6,
    "games": 32,
    "avg": 2.88,
    "regular_score": -442.6,
    "semi_score": 0,
    "regular_games": 32,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 1
  },
  {
    "rank": 39,
    "name": "小林剛",
    "score": -445,
    "games": 25,
    "avg": 2.92,
    "regular_score": -445,
    "semi_score": 0,
    "regular_games": 25,
    "semi_games": 0,
    "score_delta": 0,
    "rank_delta": 1
  },
  {
    "rank": 40,
    "name": "鈴木たろう",
    "score": -454.9,
    "games": 32,
    "avg": 2.76,
    "regular_score": -334.9,
    "semi_score": -120,
    "regular_games": 29,
    "semi_games": 3,
    "score_delta": -24,
    "rank_delta": -2
  }
];
window.MLEAGUE_UPDATED = "2026/04/17";
