// Generated by scripts/build.js. Do not edit.
window.MLEAGUE_HISTORY = [
  {
    "date": "2026-09-13",
    "observedAt": "2026-09-14T15:48:24.855Z",
    "ten_pt": 0,
    "ten_bk": 0,
    "aji_pt": 0,
    "aji_bk": 0,
    "sat_pt": 0,
    "sat_bk": 0,
    "baseline": true
  },
  {
    "date": "2026-09-14",
    "observedAt": "2026-09-14T15:48:24.855Z",
    "ten_pt": 54.7,
    "ten_bk": 144.6,
    "aji_pt": -56.3,
    "aji_bk": -188.4,
    "sat_pt": 21.1,
    "sat_bk": 43.8,
    "dateKind": "result"
  },
  {
    "date": "2026-09-15",
    "observedAt": "2026-09-15T18:36:37.398Z",
    "ten_pt": 37.8,
    "ten_bk": 163.6,
    "aji_pt": -39.7,
    "aji_bk": -68.9,
    "sat_pt": -48.3,
    "sat_bk": -94.7,
    "dateKind": "result"
  },
  {
    "date": "2026-09-17",
    "observedAt": "2026-09-17T20:08:31.091Z",
    "ten_pt": 94.5,
    "ten_bk": 285.9,
    "aji_pt": 17.3,
    "aji_bk": 54.3,
    "sat_pt": -114.2,
    "sat_bk": -340.2,
    "dateKind": "result"
  },
  {
    "date": "2026-09-18",
    "observedAt": "2026-09-18T19:29:49.303Z",
    "ten_pt": 124.2,
    "ten_bk": 437.5,
    "aji_pt": -74.9,
    "aji_bk": -159.8,
    "sat_pt": -114.2,
    "sat_bk": -277.7,
    "dateKind": "result"
  },
  {
    "date": "2026-09-21",
    "observedAt": "2026-09-22T17:16:13.626Z",
    "ten_pt": 134.3,
    "ten_bk": 409,
    "aji_pt": -145.3,
    "aji_bk": -429.8,
    "sat_pt": 4.9,
    "sat_bk": 20.8,
    "dateKind": "result",
    "recovery": {
      "source": "https://m-league.jp/games/",
      "matchIds": [
        "js-modal-key20260921-5/1",
        "js-modal-key20260921-5/2",
        "js-modal-key20260921-6/1",
        "js-modal-key20260921-6/2"
      ]
    }
  },
  {
    "date": "2026-09-22",
    "observedAt": "2026-09-22T17:16:13.626Z",
    "ten_pt": 195.8,
    "ten_bk": 462.1,
    "aji_pt": -50.8,
    "aji_bk": -277.7,
    "sat_pt": -19.7,
    "sat_bk": -184.4,
    "dateKind": "result",
    "recovery": {
      "source": "https://m-league.jp/games/",
      "matchIds": [
        "js-modal-key20260922-7/1",
        "js-modal-key20260922-7/2",
        "js-modal-key20260922-8/1",
        "js-modal-key20260922-8/2"
      ]
    }
  },
  {
    "date": "2026-09-24",
    "observedAt": "2026-09-24T19:20:07.539Z",
    "ten_pt": 175.1,
    "ten_bk": 258.4,
    "aji_pt": 6.1,
    "aji_bk": -248.6,
    "sat_pt": 85.7,
    "sat_bk": -9.8,
    "dateKind": "result"
  }
];
window.MLEAGUE_HISTORY_UPDATED = "2026-09-24";
