// Generated by scripts/build.js. Do not edit.
window.MLEAGUE_HISTORY = [
  {
    "date": "2026-09-13",
    "observedAt": "2026-09-14T15:48:24.855Z",
    "ten_pt": 0,
    "ten_bk": 0,
    "aji_pt": 0,
    "aji_bk": 0,
    "sat_pt": 0,
    "sat_bk": 0,
    "baseline": true
  },
  {
    "date": "2026-09-14",
    "observedAt": "2026-09-14T15:48:24.855Z",
    "ten_pt": 54.7,
    "ten_bk": 144.6,
    "aji_pt": -56.3,
    "aji_bk": -188.4,
    "sat_pt": 21.1,
    "sat_bk": 43.8,
    "dateKind": "result"
  }
];
window.MLEAGUE_HISTORY_UPDATED = "2026-09-14";
