'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { readJSON, readAssignment, atomicWrite, assertClean } = require('../lib/store');
const { validateSeason, round } = require('../lib/model');
const config = require('../config/season');

function withDeltas(season) {
  const prev = season.history.at(-2);
  const map = new Map((prev?.players || []).map(p => [p.name, p]));
  return season.players.map(p => ({ ...p, score_delta: map.has(p.name) ? round(p.score - map.get(p.name).score) : season.legacy ? p.score_delta : null, rank_delta: map.has(p.name) ? map.get(p.name).rank - p.rank : season.legacy ? p.rank_delta : null }));
}

function build(root = path.join(__dirname, '..')) {
  const folder = path.join(root, 'data/seasons');
  const seasons = fs.readdirSync(folder).filter(n => /^\d{4}-\d{2}\.json$/.test(n)).sort().reverse().map(n => validateSeason(readJSON(path.join(folder, n))));
  const active = seasons.find(s => s.id === config.id);
  if (!active) throw new Error('Active season missing');
  for (const [file, variable] of [['data.js', 'MLEAGUE_PLAYERS'], ['history.js', 'MLEAGUE_HISTORY'], ['app-data.js', 'MLEAGUE_APP']]) {
    if (fs.existsSync(path.join(root, file))) readAssignment(path.join(root, file), variable);
  }
  for (const s of seasons) s.players = withDeltas(s);
  for (const name of ['index.html', 'charts.html', 'app.js', 'style.css']) assertClean(fs.readFileSync(path.join(root, name), 'utf8'), name);
  const banner = '// Generated by scripts/build.js. Do not edit.\n';
  const appData = banner + `window.MLEAGUE_APP = ${JSON.stringify({ schemaVersion: 2, activeSeason: config.id, seasons })};\n`;
  const playerData = banner + `window.MLEAGUE_PLAYERS = ${JSON.stringify(active.players, null, 2)};\nwindow.MLEAGUE_UPDATED = ${JSON.stringify(active.resultDate)};\n`;
  const historyData = banner + `window.MLEAGUE_HISTORY = ${JSON.stringify(active.history.map(({ players, stages, ...row }) => row), null, 2)};\nwindow.MLEAGUE_HISTORY_UPDATED = ${JSON.stringify(active.resultDate)};\n`;
  const dest = path.join(root, 'dist');
  fs.mkdirSync(dest, { recursive: true });
  for (const [name, contents] of [['app-data.js', appData], ['data.js', playerData], ['history.js', historyData]]) {
    atomicWrite(path.join(root, name), contents);
    atomicWrite(path.join(dest, name), contents);
  }
  for (const name of ['index.html', 'charts.html', 'app.js', 'style.css']) fs.copyFileSync(path.join(root, name), path.join(dest, name));
  for (const name of ['assets', 'archive']) if (fs.existsSync(path.join(root, name))) fs.cpSync(path.join(root, name), path.join(dest, name), { recursive: true });
  const vendor = path.join(dest, 'vendor');
  fs.mkdirSync(vendor, { recursive: true });
  fs.copyFileSync(path.join(root, 'node_modules/chart.js/dist/chart.umd.js'), path.join(vendor, 'chart.umd.js'));
  fs.copyFileSync(path.join(root, 'node_modules/lucide/dist/umd/lucide.js'), path.join(vendor, 'lucide.js'));
  fs.mkdirSync(path.join(root, 'vendor'), { recursive: true });
  for (const name of ['chart.umd.js', 'lucide.js']) fs.copyFileSync(path.join(vendor, name), path.join(root, 'vendor', name));
  console.log(`Build: ${seasons.map(s => `${s.id} (${s.history.length} snapshots)`).join(', ')} -> dist/`);
  return { seasons, active };
}

if (require.main === module) build();
module.exports = { build, withDeltas };
